name: rna_design_optim
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - tensorflow
  - matplotlib
  - jupyterlab
  - scipy
  - h5py
  - pillow
  - seaborn
  - protobuf
  - grpcio
  - pip
  - pip:
      - biopython==1.83
      - tqdm==4.66.2
      - transformers==4.39.3
      - ViennaRNA==2.6.4
      - rna-tools==3.20.3
      - RnaBench==0.1.2
